### PR TITLE
Feature | Issue #5 | Fundamental React Content

### LINKED ISSUE #5: Add content of fundamental react topics
Add content (talks, articles, podcasts) of decided fundamental react topics:
1. State and Props
2. Hooks
3. Rendering
4. Patterns
5. Testing

### PR DESCRIPTION
**Pull request by Sheraz064-ai**
## Description
This PR closes #5

Changes proposed in this pull request:
- Added Blogs/Articles and Talks for States and Props.
- Added Blogs/Articles, Talks, and Podcasts for Hooks.
- Added Blogs/Articles, Talks, and Podcasts for Rendering.
- Added Blogs/Articles, Talks, and Podcasts for Patterns.
- Added Blogs/Articles for Testing.

## Checklist
- [x] Make sure you are making a pull request against the **main branch**
- [x] Check the PR title and branch naming structure matched with our [guidelines](../CONTRIBUTING.md) 
- Please check the type of change your PR introduces:
  - [x] New feature
  - [ ] Bug in content and documentation
  - [ ] Fix in content and documentation
  - [ ] Other changes

## Screenshots
Screenshot 2022-08-28 at 1 46 30 PM
Screenshot 2022-08-28 at 1 47 26 PM
Screenshot 2022-08-28 at 1 47 38 PM
Screenshot 2022-08-28 at 1 47 45 PM
Screenshot 2022-08-28 at 1 47 56 PM

### CODE REVIEW

**Review by nabeel-shakeel — APPROVED** [review]
Wonderful 🚀

**Comment by nabeel-shakeel** [comment]
@Sheraz064-ai: All is good, but to merge this PR, you need to signed your commit 
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Review by nabeel-shakeel — CHANGES_REQUESTED** [review]
Signed your commit

**Comment by Sheraz064-ai** [comment]
> Signed your commit

Added Signed Commit

**Comment by nabeel-shakeel** [comment]
@Sheraz064-ai: This commit should also be signed  29c79fb663483705fd25c5e0e9b7f3591c1d98b3

**Comment by Sheraz064-ai** [comment]
Signed Commit has been added
@nabeel-shakeel

**Review by nabeel-shakeel — APPROVED** [review]

**Pull request merged**
